#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlkoTrip3.Resource", IsApplication=true)]

namespace AlkoTrip3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070002
			public const int button1 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int button2 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int button5 = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int buttonLayout = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int comp1 = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int comp2 = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int ingridTitleLayout = 2131165189;
			
			// aapt resource value: 0x7f070009
			public const int less1 = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int less2 = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int mainLayout = 2131165184;
			
			// aapt resource value: 0x7f07000b
			public const int more1 = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int more2 = 2131165200;
			
			// aapt resource value: 0x7f070008
			public const int name1 = 2131165192;
			
			// aapt resource value: 0x7f07000d
			public const int name2 = 2131165197;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int val1 = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int val2 = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
